### ISSUE TITLE
Is it possible to add a new api to get pcie devices

### ISSUE THREAD

**Issue by chenfengyuan** [hankjordan/devices#2]
Sometimes it's slow to call `lsusb`, about  5 seconds, but I only need pcie device infos.
Is it possible to add a new api to get pcie devices only?
Or add two apis, one for pcie devices, and one for usb devices.

**Comment by hankjordan** [comment]
Fixed in [#3e910d7](https://github.com/hankjordan/devices/commit/3e910d7755c9d7a2ae9548aa2cf9ee2c61afcfee)
